name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu-build:
    name: Build - Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen libncurses5
  
    - name: Install clang-format-10
      run: |
        cd ${{github.workspace}}
        wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        tar -xf ${{github.workspace}}/clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        cp ${{github.workspace}}/clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang-format ${{github.workspace}}/clang-format-10
        rm -rf clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-16.04 clang+llvm-10.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        echo ${{github.workspace}} >> $GITHUB_PATH

    - name: Install pip packages
      run: pip install -r third_party/requirements.txt

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUR_ENABLE_TESTS=ON

    - name: Generate source from spec, check for uncommitted diff
      run: cmake --build ${{github.workspace}}/build --target check-generated

    - name: Check source code is formatted
      run: cmake --build ${{github.workspace}}/build --target check-cppformat

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  windows-build:
    name: Build - Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install prerequisites
        run: python3 -m pip install -r third_party/requirements.txt

      - name: Configure CMake
        run: cmake -DCMAKE_POLICY_DEFAULT_CMP0094=NEW -DUR_ENABLE_TESTS=ON -B ${{github.workspace}}/build

      - name: Generate source from spec, check for uncommitted diff
        run: cmake --build ${{github.workspace}}/build --target check-generated --config ${{env.BUILD_TYPE}}

      - name: Build all
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
